from pathlib import Path

path = Path('docs/OPERATIONS_COMPLIANCE_MATRIX.md')
lines = path.read_text().splitlines()

rows = {
    'ORD-001': "| ORD-001 | Two-panel desktop layout with persistent cart. | Orders | `apps/operations/src/app/OrdersWorkspace.tsx`; `OrdersCart.tsx`; `styles/orders.css` | — | Production build/strict typecheck | IMPLEMENTED_NOT_VALIDATED | Desktop persistent cart and separate mobile cart sheet implemented; no manual rendered interaction QA recorded yet. |",
    'ORD-002': "| ORD-002 | Dynamic categories. | Orders | `apps/operations/src/app/OrdersWorkspace.tsx` | Local configuration snapshot | Workspace configuration loading; production build | IMPLEMENTED_NOT_VALIDATED | Active categories come from configuration, are sort-ordered, and no `All` category is introduced; manual interaction QA still pending. |",
    'ORD-003': "| ORD-003 | Direct +/- product quantities. | Orders | `packages/domain/src/draftOperations.ts`; `apps/operations/src/app/OrdersWorkspace.tsx` | Durable `OrderDraftStore` | `packages/domain/src/draftOperations.test.ts` | IMPLEMENTED_NOT_VALIDATED | Domain add/decrement semantics and deterministic most-recent removal are tested; rendered control interaction has no E2E evidence yet. |",
    'ORD-004': "| ORD-004 | No Add to Cart button. | Orders | `apps/operations/src/app/OrdersWorkspace.tsx` | — | Production build | IMPLEMENTED_NOT_VALIDATED | Product cards expose direct +/- only; manual rendered audit still pending. |",
    'ORD-005': "| ORD-005 | Optional product image. | Orders | `apps/operations/src/app/OrdersWorkspace.tsx`; `styles/orders.css` | Configuration `imageKey` | Production build | IMPLEMENTED_NOT_VALIDATED | Optional contain image plus deterministic fallback implemented; visual QA still pending. |",
    'ORD-006': "| ORD-006 | Quick Info description. | Orders | `apps/operations/src/app/OrdersWorkspace.tsx` | Configuration `description` | Production build | IMPLEMENTED_NOT_VALIDATED | Non-control card area opens Quick Info using configured description; interaction QA still pending. |",
    'ORD-007': "| ORD-007 | Extras standalone + modifiers. | Orders | `packages/domain/src/draftOperations.ts`; `apps/operations/src/app/ProductCustomizer.tsx` | Configuration products/modifiers/links | `packages/domain/src/draftOperations.test.ts` | IMPLEMENTED_NOT_VALIDATED | Standalone extras remain normal configured products; product modifiers enforce configured eligibility/max quantity. Customizer interaction QA still pending. |",
    'ORD-008': "| ORD-008 | Required combo beverage per combo unit. | Orders | `packages/domain/src/draftOperations.ts`; `ProductCustomizer.tsx`; `orderValidation.ts` | Configuration combo beverage options | `packages/domain/src/draftOperations.test.ts` | PASS | Domain rejects missing/unavailable/disallowed combo beverages and requires one beverage selection per combo unit. |",
    'ORD-009': "| ORD-009 | Item note and order note separate. | Orders | `packages/domain/src/orderDraft.ts`; `ProductCustomizer.tsx`; `OrdersCart.tsx` | Immutable order snapshot | Receipt rendering test; production build | IMPLEMENTED_NOT_VALIDATED | Separate typed fields and separate UI editors exist; full renderer interaction path has no E2E evidence yet. |",
    'ORD-010': "| ORD-010 | Delivery-only customer fields. | Orders | `apps/operations/src/app/OrdersCart.tsx` | Delivery fulfillment snapshot | Production build | IMPLEMENTED_NOT_VALIDATED | Name/phone/zone/address/fee section renders only for configured Delivery behavior; manual interaction QA still pending. |",
    'ORD-011': "| ORD-011 | Delivery requires phone/name/zone/address. | Orders | `packages/domain/src/orderValidation.ts`; `OrdersCart.tsx` | Immutable Delivery snapshot | Strict typecheck; successful Delivery integration path | IMPLEMENTED_NOT_VALIDATED | Validation rules are implemented and source-local errors are wired, but missing-field interaction cases do not yet have dedicated automated UI coverage. |",
    'ORD-012': "| ORD-012 | Egyptian phone normalization/autofill. | Orders | `packages/domain/src/phone.ts`; `OrdersWorkspace.tsx`; `OperationsOrdersService` | Customer contacts repository | `packages/domain/src/phone.test.ts`; Delivery customer integration test | IMPLEMENTED_NOT_VALIDATED | Normalization and successful-contact learning are tested; renderer autofill interaction is implemented but has no E2E evidence yet. |",
    'ORD-013': "| ORD-013 | Zone auto fee + worker can manually edit fee. | Orders | `packages/domain/src/draftOperations.ts`; `OrdersCart.tsx` | Delivery configured/final fee snapshots | `draftOperations.test.ts`; Delivery checkout integration test | PASS | Zone selection snapshots configured fee, initializes final fee, and checkout preserves a worker-edited final fee separately. |",
    'ORD-014': "| ORD-014 | Fixed discount applies to items subtotal only. | Orders | `packages/domain/src/pricing.ts`; `OrdersCart.tsx` | Immutable order pricing snapshot | `packages/domain/src/pricing.test.ts` | PASS | Exact pricing helper validates discount against item subtotal and adds Delivery fee outside the discounted item subtotal. |",
    'ORD-015': "| ORD-015 | Exact money semantics. | Orders | `packages/domain/src/money.ts`; `payment.ts`; `pricing.ts`; `MoneyInput.tsx` | Integer minor units | Money/pricing/payment tests | PASS | Orders calculations and editable money parsing use branded integer minor units; no floating-point accounting path is used. |",
    'ORD-016': "| ORD-016 | Payment method has stable logic type separate from label. | Orders | `packages/domain/src/catalog.ts`; `payment.ts` | Payment-method configuration snapshot | `packages/domain/src/payment.test.ts` | PASS | Cash behavior is driven by stable `logicType`, including a test with a non-`Cash` display label. |",
    'ORD-017': "| ORD-017 | Payment selection resets every successful order. | Orders | `packages/application/src/orders.ts` | Durable post-checkout draft | SQLite Orders integration test | PASS | Successful checkout rotates the draft and resets payment to `{ mode: 'NONE' }`. |",
    'ORD-018': "| ORD-018 | Order type resets to first active configured type after success. | Orders | `packages/application/src/orders.ts` | Durable post-checkout draft | SQLite Orders integration test | PASS | Successful checkout creates the next draft with the first active configured order type. |",
    'ORD-019': "| ORD-019 | Current Operator persists. | Orders | `OperationsOrdersService`; existing session service/shell | Worker session + immutable order operator snapshot | SQLite Orders/session integration tests | PASS | Checkout snapshots the authenticated operator and does not terminate/switch the current worker session. |",
    'ORD-020': "| ORD-020 | Split payment max 2; second amount is remainder. | Orders | `packages/domain/src/payment.ts`; `OrdersCart.tsx` | Immutable payment snapshots | `packages/domain/src/payment.test.ts` | PASS | Split model contains exactly A/B methods and calculates B as exact total minus Amount A; duplicate methods are rejected. |",
    'ORD-021': "| ORD-021 | Cash Received / Change behavior. | Orders | `packages/domain/src/payment.ts`; `OrdersCart.tsx` | Immutable payment snapshots | Payment tests; SQLite Cash checkout integration test | PASS | Cash Received is required and cannot be below allocation; Change is calculated exactly and persisted in the order snapshot. |",
    'ORD-022': "| ORD-022 | Smart tender suggestions. | Orders | `packages/domain/src/tender.ts`; `OrdersCart.tsx` | — | `packages/domain/src/tender.test.ts` | PASS | Domain helper produces exact common-Egyptian-note tender suggestions and renderer consumes the helper directly. |",
    'ORD-023': "| ORD-023 | Validate all before mutations. | Orders | `packages/domain/src/orderValidation.ts`; `packages/application/src/orders.ts` | Single local transaction starts only after validation | SQLite Orders validation-failure integration test | PASS | Invalid checkout returns `VALIDATION_ERROR`; orders, inventory, audit, outbox, numbering, and durable draft state remain mutation-free. |",
    'ORD-024': "| ORD-024 | Durable local commit before print. | Orders | `OperationsOrdersService`; `@tux/printing`; Electron/browser printer adapters | Local order transaction before printer port | SQLite print integration tests; receipt tests | PASS | Fresh order is committed before printer invocation; print failure returns a post-commit warning and cannot roll back the saved order. |",
    'ORD-025': "| ORD-025 | Local failure blocks checkout and keeps cart. | Orders | `OperationsOrdersService`; durable draft stores | SQLite transaction + draft store | Injected inventory-failure integration test | PASS | Injected local persistence failure rolls back order/number/inventory/audit/outbox and preserves the checkout-intent draft. |",
    'ORD-026': "| ORD-026 | Offline local save counts as success and queues cloud. | Orders | `OperationsOrdersService` | Local `ORDER_PLACED` durable outbox event | SQLite checkout integration test | PASS | Checkout has no remote dependency; local commit succeeds with remote unconfigured and writes `ORDER_PLACED` to durable outbox in the same transaction. |",
    'ORD-027': "| ORD-027 | Idempotent duplicate prevention. | Orders | `OperationsOrdersService`; checkout intent key | Unique idempotency lookup/constraints | SQLite stale-intent replay integration test | PASS | Replayed committed intent returns the existing Order and does not duplicate order, inventory, numbering, audit/outbox, or automatic print effects. |",
    'ORD-028': "| ORD-028 | Business Day, not calendar date, owns display order numbering. | Orders | Business Day domain + `OperationsOrdersService` | Business-Day scoped counter and unique order constraint | Business Day tests; SQLite Orders integration test | PASS | Checkout allocates from the open Business Day counter; no calendar-date reset logic participates. |",
    'ORD-029': "| ORD-029 | Global immutable order ID never resets. | Orders | Branded `OrderId`; `OperationsOrdersService` | UUID primary order identity | SQLite Orders/idempotency integration tests | PASS | Each placed order uses UUID identity independent of Business-Day display numbering; replay returns the same immutable Order ID. |",
    'ORD-031': "| ORD-031 | Calculated inventory shortage alone does not block checkout. | Orders | `OperationsOrdersService` inventory movement append | Append-only inventory ledger | SQLite successful checkout integration test | PASS | Checkout does not require a positive calculated balance; test fixture successfully places an order without preloading positive stock balance and appends exact consumption. |",
    'ORD-032': "| ORD-032 | Sold Out blocks sellability. | Orders | `packages/domain/src/draftOperations.ts`; `OrdersWorkspace.tsx` | Configuration `soldOut` flag | `packages/domain/src/draftOperations.test.ts` | PASS | Domain rejects adding a Sold Out product and renderer disables its add control. |",
    'ORD-033': "| ORD-033 | Placed orders immutable. | Orders | `packages/domain/src/models.ts`; persistence `OrderRepository`; receipt/reprint path | Order repository exposes `insert`, not general update | SQLite Orders/print integration tests | PASS | Checkout persists an immutable `OrderSnapshot`; reprint reads by ID and creates no order mutation. Later corrections must use explicit audited transitions. |",
}

found = set()
for index, line in enumerate(lines):
    for requirement_id, replacement in rows.items():
        if line.startswith(f'| {requirement_id} |'):
            lines[index] = replacement
            found.add(requirement_id)
            break

missing = sorted(set(rows) - found)
if missing:
    raise SystemExit(f'Missing compliance rows: {missing}')

path.write_text('\n'.join(lines) + '\n')
