import type { Category, Product } from "@/lib/menu-data";

export const EXTRA_CATEGORY: Category = {
  id: "extras",
  name: "Extras",
  slug: "extras",
  sort_order: 7,
};

export const EXTRA_PRODUCTS: Product[] = [
  {
    id: "extra-smashed-patty",
    category_id: "extras",
    name: "Extra Smashed Patty",
    description: "Add one extra smashed beef patty to your sandwich.",
    price: 60,
    image_url: "",
    is_best_seller: false,
    is_available: true,
    sort_order: 1,
  },
  {
    id: "extra-bacon",
    category_id: "extras",
    name: "Bacon",
    description: "Add bacon to your sandwich.",
    price: 30,
    image_url: "",
    is_best_seller: false,
    is_available: true,
    sort_order: 2,
  },
  {
    id: "extra-cheese",
    category_id: "extras",
    name: "Cheese",
    description: "Add extra cheese to your sandwich.",
    price: 25,
    image_url: "",
    is_best_seller: false,
    is_available: true,
    sort_order: 3,
  },
  {
    id: "extra-ranch",
    category_id: "extras",
    name: "Ranch",
    description: "Add ranch sauce.",
    price: 20,
    image_url: "",
    is_best_seller: false,
    is_available: true,
    sort_order: 4,
  },
  {
    id: "extra-mushroom",
    category_id: "extras",
    name: "Mushroom",
    description: "Add mushrooms to your sandwich.",
    price: 30,
    image_url: "",
    is_best_seller: false,
    is_available: true,
    sort_order: 5,
  },
  {
    id: "extra-caramelized-onion",
    category_id: "extras",
    name: "Caramelized Onion",
    description: "Add caramelized onion.",
    price: 15,
    image_url: "",
    is_best_seller: false,
    is_available: true,
    sort_order: 6,
  },
  {
    id: "extra-jalapeno",
    category_id: "extras",
    name: "Jalapeno",
    description: "Add jalapeno slices.",
    price: 20,
    image_url: "",
    is_best_seller: false,
    is_available: true,
    sort_order: 7,
  },
  {
    id: "extra-tux-sauce",
    category_id: "extras",
    name: "Tux Sauce",
    description: "Add extra TUX sauce.",
    price: 20,
    image_url: "",
    is_best_seller: false,
    is_available: true,
    sort_order: 8,
  },
  {
    id: "extra-bun",
    category_id: "extras",
    name: "Extra Bun",
    description: "Add one extra bun.",
    price: 20,
    image_url: "",
    is_best_seller: false,
    is_available: true,
    sort_order: 9,
  },
  {
    id: "extra-pickle",
    category_id: "extras",
    name: "Pickle",
    description: "Add extra pickles.",
    price: 15,
    image_url: "",
    is_best_seller: false,
    is_available: true,
    sort_order: 10,
  },
  {
    id: "extra-sauce-selection",
    category_id: "extras",
    name: "BBQ/Ketchup/Sweet Chili/HotSauce",
    description: "Choose one extra sauce: BBQ, ketchup, sweet chili, or hot sauce.",
    price: 20,
    image_url: "",
    is_best_seller: false,
    is_available: true,
    sort_order: 11,
  },
  {
    id: "extra-tux-hawawshi-sauce",
    category_id: "extras",
    name: "Tux Hawawshi Sauce",
    description: "Add extra TUX Hawawshi sauce.",
    price: 20,
    image_url: "",
    is_best_seller: false,
    is_available: true,
    sort_order: 12,
  },
  {
    id: "extra-mozarella",
    category_id: "extras",
    name: "Mozarella",
    description: "Add extra mozarella.",
    price: 25,
    image_url: "",
    is_best_seller: false,
    is_available: true,
    sort_order: 13,
  },
  {
    id: "extra-doppy-fries",
    category_id: "extras",
    name: "Extra Doppy Fries",
    description: "Add extra Doppy fries.",
    price: 95,
    image_url: "",
    is_best_seller: false,
    is_available: true,
    sort_order: 14,
  },
  {
    id: "extra-tux-fries",
    category_id: "extras",
    name: "Extra Tux Fries",
    description: "Add extra TUX fries.",
    price: 80,
    image_url: "",
    is_best_seller: false,
    is_available: true,
    sort_order: 15,
  },
  {
    id: "extra-wedges",
    category_id: "extras",
    name: "Extra Wedges",
    description: "Add extra wedges.",
    price: 30,
    image_url: "",
    is_best_seller: false,
    is_available: true,
    sort_order: 16,
  },
];
