from pathlib import Path
import re
R=Path.cwd()
def f(p): return (R/p).read_text()
def w(p,s): (R/p).write_text(s)
def sub(s,p,r,n):
 c=len(re.findall(p,s,re.S))
 if c!=1: raise SystemExit(f'{n}: expected 1 match, got {c}')
 return re.sub(p,r,s,count=1,flags=re.S)
def add(p,mark,block):
 s=f(p)
 if mark in s: raise SystemExit(f'duplicate marker in {p}')
 w(p,s.rstrip()+'\n\n'+block.strip()+'\n')

add('apps/operations/src/styles/orders.css','TUX follow-up: Current Order and delivery totals','''/* TUX follow-up: Current Order and delivery totals */\n.line-quantity-stepper{display:grid;grid-template-columns:44px 40px 44px;height:44px;border:1px solid var(--tux-border-subtle);border-radius:var(--tux-radius-sm);overflow:hidden;background:var(--tux-surface-subtle);flex:0 0 auto}.line-quantity-stepper button{width:44px;height:44px;min-height:44px;border:0;border-radius:0;background:transparent;padding:0}.line-quantity-stepper output{display:grid;place-items:center;min-width:40px;font-size:15px;line-height:20px;font-weight:600;font-variant-numeric:tabular-nums}.cart-totals dl>.delivery-total-editor{display:grid;gap:4px}.delivery-total-editor .money-field{display:grid;grid-template-columns:minmax(0,1fr) minmax(128px,160px);align-items:center;gap:12px}.delivery-total-editor .money-input-wrap{min-height:44px}.delivery-total-editor .money-input-wrap input{height:44px;text-align:right}.delivery-zone-reference{grid-column:1/-1;font-size:12px;line-height:16px;color:var(--tux-text-secondary);text-align:right}''')
p='apps/operations/src/styles/premium.css'; s=f(p)
s=sub(s,r'@container tux-menu \(min-width: 1071px\)', '@container tux-menu (min-width: 900px)','3 column breakpoint'); w(p,s)
add(p,'TUX follow-up: category/search/operator controls','''/* TUX follow-up: category/search/operator controls */\n.operations-header .operator-trigger{display:inline-flex;align-items:center;gap:6px}.operator-user-icon{width:20px;height:20px;flex:0 0 20px}.menu-toolbar .product-family-filter{display:flex;width:fit-content;max-width:100%;justify-self:start;gap:6px;padding:0;border:0;background:transparent;overflow-x:auto;scrollbar-width:none;-ms-overflow-style:none}.menu-toolbar .product-family-filter::-webkit-scrollbar{display:none}.menu-toolbar .category-search-inline{position:relative;display:grid;grid-template-columns:44px minmax(0,1fr) 44px;width:clamp(240px,21vw,300px);max-width:320px;min-height:44px;align-items:center;gap:0;border:1px solid var(--tux-border-subtle);border-radius:var(--tux-radius-sm);background:var(--tux-surface-subtle);overflow:hidden}.menu-toolbar .category-search-inline .category-search-glyph{width:20px;height:20px;place-self:center;margin:0}.menu-toolbar .category-search-inline input{width:100%;min-width:0;height:44px;min-height:44px;border:0;background:transparent;padding:0 8px;font-size:14px;line-height:18px;font-weight:400;outline:none}.menu-toolbar .category-search-inline .category-search-clear{width:44px;min-width:44px;height:44px;border:0;border-left:1px solid color-mix(in srgb,var(--tux-border-subtle) 60%,transparent);border-radius:0;background:transparent}.menu-toolbar .category-editor-list{display:flex;flex-wrap:wrap;gap:8px;overflow:visible;padding-bottom:0}.menu-toolbar .category-editor-item{flex:0 0 auto;min-height:44px}.line-actions .line-quantity-stepper{flex:0 0 auto}.line-actions .line-quantity-stepper button{width:44px;min-width:44px;height:44px;min-height:44px;border:0;border-radius:0;background:transparent;padding:0}.line-actions .line-quantity-stepper button:hover:not(:disabled){background:var(--tux-accent-hover-soft)}.line-actions .line-quantity-stepper output{color:var(--tux-text-primary)}''')
add('apps/operations/src/styles/final-pos-corrections.css','TUX follow-up: compact mobile Operations shell','''/* TUX follow-up: compact mobile Operations shell */\n@media(max-width:54rem){.operations-shell{--tux-floating-header-space:7rem;padding-top:var(--tux-space-2)}.operations-header{grid-template-areas:'brand actions' 'nav nav';grid-template-columns:auto minmax(0,1fr);gap:4px 8px;width:calc(100% - 16px);height:auto;min-height:0;margin:0 8px 8px;padding:6px 8px}.operations-brand-slot{grid-area:brand}.header-actions{grid-area:actions;justify-self:end}.operations-nav{grid-area:nav;width:100%;min-width:0;justify-self:stretch;overflow-x:auto;scrollbar-width:none;-ms-overflow-style:none;padding-bottom:0}.operations-nav::-webkit-scrollbar{display:none}.operations-header .tux-brand{width:auto;height:36px;min-width:0;min-height:36px;max-height:36px;padding:0}.operations-header .nav-item,.operations-header .operator-trigger{min-height:44px}.menu-toolbar{gap:4px;margin-inline:8px;padding:4px 6px 6px}.menu-toolbar .category-navigation{grid-template-columns:minmax(0,1fr) auto;gap:4px}.menu-toolbar .category-rail{min-width:0;overflow-x:auto;scrollbar-width:none;-ms-overflow-style:none}.menu-toolbar .category-rail::-webkit-scrollbar{display:none}.menu-toolbar .category-rail .category-tab{height:44px;min-height:44px;padding-inline:12px}.menu-toolbar .category-nav-actions{gap:4px}.menu-toolbar .category-nav-actions>button{box-sizing:border-box;width:44px;min-width:44px;height:44px;min-height:44px;padding:0}.menu-toolbar .product-family-filter{overflow-x:auto;scrollbar-width:none;-ms-overflow-style:none}.menu-toolbar .product-family-filter::-webkit-scrollbar{display:none}.product-grid{padding-bottom:calc(76px + env(safe-area-inset-bottom))}.mobile-cart-overlay .orders-cart{display:grid;grid-template-rows:auto minmax(0,1fr) auto;min-height:0;height:100%}.mobile-cart-overlay .cart-scroll{min-height:0;overflow-y:auto;padding-bottom:16px;scroll-padding-bottom:16px}.mobile-cart-overlay .cart-totals{position:relative;inset:auto}}''')
add('apps/operations/src/styles/expenses.css','Approved follow-up refinement: compact operational Expenses layout.','''/* Approved follow-up refinement: compact operational Expenses layout. */\n.expenses-heading h1{font-size:28px;line-height:34px;font-weight:600}.expenses-heading>div:first-child>p:last-child{font-size:14px;line-height:18px}.expenses-total{width:184px;min-width:176px;max-width:192px;border-radius:12px;box-shadow:none}.expenses-total span{font-size:12px;line-height:16px;font-weight:600;letter-spacing:0}.expenses-total strong{font-size:22px;line-height:26px;font-weight:600;font-variant-numeric:tabular-nums}.expense-add-card,.expense-ledger,.expense-dialog{border-radius:12px;box-shadow:none}.expense-add-card{padding:20px}.expense-add-heading{align-items:center;margin-bottom:16px}.expense-add-heading h2{font-size:20px;line-height:24px;font-weight:600}.expense-fields input,.expense-fields textarea,.expense-choice,.expense-note-disclosure{min-height:44px}.expense-paid-helper{margin:6px 0 0;color:var(--tux-text-secondary);font-size:13px;line-height:16px;font-weight:400}.expense-note-disclosure{grid-column:1/-1;justify-self:start;border:1px solid var(--tux-border-subtle);border-radius:var(--tux-radius-sm);background:var(--tux-surface-raised);padding:0 14px;color:var(--tux-text-primary);font-size:14px;line-height:18px;font-weight:500}.expense-note-disclosure:hover:not(:disabled){background:var(--tux-accent-hover-soft)}.expense-add-card>.expense-submit{min-height:48px;font-size:16px;line-height:20px;font-weight:600}.expense-ledger-heading{padding:16px 20px}.expense-ledger-heading h2{font-size:18px;line-height:22px;font-weight:600}.expense-ledger-heading>span{font-size:13px;line-height:16px;font-weight:400}.expense-ledger-columns{display:grid;grid-template-columns:5.5rem minmax(0,1fr) minmax(8rem,auto) auto;gap:var(--tux-space-4);padding:10px var(--tux-space-6);border-bottom:1px solid var(--tux-border-subtle);color:var(--tux-text-secondary);font-size:12px;line-height:16px;font-weight:600}.expense-ledger-columns span:nth-child(3),.expense-ledger-columns span:nth-child(4){text-align:right}.expense-row-amount{font-variant-numeric:tabular-nums}.expense-empty{min-height:8rem}@media(max-width:54rem){.expenses-total{width:184px;min-width:176px;max-width:192px}.expense-ledger-columns{display:none}}''')
add('apps/operations/src/styles/bulk-stock.css','Approved follow-up refinement: restrained Bulk Stock surfaces.','''/* Approved follow-up refinement: restrained Bulk Stock surfaces. */\n.bulk-stock-page-heading h1{font-size:28px;line-height:34px;font-weight:600}.bulk-stock-page-heading>div>p:last-child{font-size:14px;line-height:18px}.bulk-stock-empty{min-height:112px;border-radius:12px;box-shadow:none;display:grid;place-content:center;gap:8px}.bulk-stock-empty h2{font-size:17px;line-height:22px;font-weight:600}.bulk-stock-empty p{font-size:14px;line-height:18px}.bulk-stock-card{padding:16px;border-radius:12px;box-shadow:none}.bulk-stock-card h2{font-size:17px;line-height:22px;font-weight:600}.bulk-stock-card-main>span{font-size:12px;line-height:16px;font-weight:600}.bulk-stock-balance{font-size:28px;line-height:34px;font-weight:600;font-variant-numeric:tabular-nums}.bulk-stock-finished-action,.bulk-stock-add-action{min-height:44px}.bulk-stock-dialog{border-radius:12px;box-shadow:none}.bulk-stock-quantity-field input{min-height:44px}.bulk-stock-quantity-field span{font-size:13px;line-height:16px}.bulk-stock-dialog>.primary-action{min-height:48px}.bulk-stock-undo{background:var(--tux-surface-panel);box-shadow:none}.bulk-stock-undo button{min-height:44px}''')

# hard scope + contract checks
for p in ['apps/operations/src/app/OrdersBoardWorkspace.tsx','apps/operations/src/styles/orders-board.css']:
 if not (R/p).exists(): raise SystemExit(f'missing protected file {p}')
req={'apps/operations/src/app/OrdersCart.tsx':['line-quantity-stepper','data-icon="plus-circle"','label="Delivery"','Amount B','Cash received'],'apps/operations/src/app/ExpensesWorkspace.tsx':['Add note','No expenses this business day','entries · Newest first'],'apps/operations/src/styles/premium.css':['@container tux-menu (min-width: 900px)']}
for p,xs in req.items():
 s=f(p)
 for x in xs:
  if x not in s: raise SystemExit(f'{p}: missing {x}')
print('approved follow-up patch applied')
